#ifndef _WHEEL_H_
#define _WHEEL_H_

#include "../util/util.h"

#define PWM_CHANNEL_INTERNAL(CHANNEL) CONCAT_EXP(_PWM_CHANNEL, CHANNEL)
#define PWM_MODULE_TIM_CH_PIN(TIMER, CHANNEL, PIN_NAME, PIN_IDX)    \
CONCAT_EXP(CONCAT_EXP(CONCAT_EXP(_GPIO_MODULE_TIM, TIMER),  \
            CONCAT_EXP(_CH, CHANNEL)),                      \
            CONCAT_EXP(CONCAT_EXP(_P, PIN_NAME),PIN_IDX))
#define PWM_TIM_START(TIMER) CONCAT_EXP(CONCAT_EXP(PWM_TIM, TIMER),_Start)
#define PWM_TIM_STOP(TIMER) CONCAT_EXP(CONCAT_EXP(PWM_TIM, TIMER),_Stop)
#define PWM_TIM_INIT(TIMER) CONCAT_EXP(CONCAT_EXP(PWM_TIM, TIMER),_Init)
#define PWM_TIM_SET_DUTY(TIMER) CONCAT_EXP(CONCAT_EXP(PWM_TIM, TIMER),_Set_Duty)

#endif
